### ISSUE TITLE
Request for integration - ESPHome Light Component (RGBW)

### ISSUE THREAD

**Issue by bigd-73** [iobroker-community-adapters/ioBroker.esphome#10]
Hello Dutchman, 

i would like to ask for integration. 

`2021-03-01 15:53:06.241 - warn: esphome.0 (11603) DeviceType Light | State-Keys {"key":3048698813,"state":false,"brightness":1,"red":1,"green":1,"blue":1,"white":1,"colorTemperature":0,"effect":"None"} | [entityStateConfig] {"config":{"objectId":"quinled_quad","key":3048698813,"name":"QuinLED_Quad","uniqueId":"esphome_developer_qlquad_dev4lightquinled_quad","supportsBrightness":true,"supportsRgb":true,"supportsWhiteValue":true,"supportsColorTemperature":false,"minMireds":0,"maxMireds":0,"effectsList":["None","My Slow Random Effect","My Fast Random Effect","My Insane Random Effect","Totally loco","Strobe Effect With Custom Values"]},"name":"Light","type":"Light","unit":""}`

Thanks
Mario

**Comment by DutchmanNL** [comment]
Implemented v0.1.1
